# Generated by Django 4.0.3 on 2023-07-26 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_salesperson_employee_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
    ]
