# Generated by Django 4.0.3 on 2023-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_appointment_canceled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='finished',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='vin',
            field=models.CharField(max_length=50),
        ),
    ]
